### PR TITLE
Fix paths

### PR DESCRIPTION
**Pull request by fromjonathan**
I think that the MERGE method was not working, so I changed the paths for these four ui assets:
 './default/public/js/ui.js', 
'./default/public/js/default.js'
'./default/public/css/ui.css', 
'./default/public/css/default.css'
Everything is loading fine now

### CODE REVIEW

**Comment by petersirka** [comment]
This is wrong because `=` is targeted to `themes` and `.` means relative path.

**Comment by fromjonathan** [comment]
I think that `=` is making the MERGE method to stop working for me. Running on node --version
v10.14.2

**Comment by petersirka** [comment]
On Windows?

**Comment by fromjonathan** [comment]
Linux

**Comment by petersirka** [comment]
Are you sure you run `node debug.js` or `node release.js` from the app directory? Because I use Ubuntu 16.04.1 LTS with Node `v10.14.1` and everything works correctly.

**Pull request closed without merging**
